name: Circe Documentation
markdown: kramdown
highlighter: rouge
# this kramdown config is for local use and I think GitHub's Jekyll ignores it
kramdown:
  input: GFM
  syntax_highlighter: rouge
baseurl: /circe
apidocs: /circe/api/
sources: https://github.com/travisbrown/circe/blob/master/

collections:
  tut:
    output: true
